import { RecipeCategory, RecipeSummary } from './types';

export const INITIAL_RECIPES: RecipeSummary[] = [
  // Breads
  { id: '1', name: 'Pandesal (Classic)', category: RecipeCategory.BREAD, isPopular: true },
  { id: '2', name: 'Ensaymada (Brioche)', category: RecipeCategory.BREAD, isPopular: true },
  { id: '3', name: 'Pan de Coco', category: RecipeCategory.BREAD, isPopular: true },
  { id: '4', name: 'Spanish Bread', category: RecipeCategory.BREAD, isPopular: true },
  { id: '5', name: 'Monay', category: RecipeCategory.BREAD, isPopular: false },
  { id: '6', name: 'Putok', category: RecipeCategory.BREAD, isPopular: false },
  { id: '7', name: 'Kalihim (Pan de Regla)', category: RecipeCategory.BREAD, isPopular: true },
  { id: '8', name: 'Bicho-Bicho (Filipino Donut)', category: RecipeCategory.BREAD, isPopular: true },
  { id: '9', name: 'Tasty Bread (Pinoy Loaf)', category: RecipeCategory.BREAD, isPopular: false },
  { id: '10', name: 'Everlasting', category: RecipeCategory.BREAD, isPopular: false },
  { id: '11', name: 'Francis', category: RecipeCategory.BREAD, isPopular: false },
  { id: '12', name: 'Kababayan', category: RecipeCategory.BREAD, isPopular: true },
  { id: '13', name: 'Pinagong', category: RecipeCategory.BREAD, isPopular: false },
  { id: '14', name: 'Bonete', category: RecipeCategory.BREAD, isPopular: false },
  { id: '15', name: 'Asado Roll', category: RecipeCategory.BREAD, isPopular: true },
  { id: '16', name: 'Cheese Bread', category: RecipeCategory.BREAD, isPopular: true },
  { id: '17', name: 'Ube Cheese Pandesal', category: RecipeCategory.BREAD, isPopular: true },
  { id: '18', name: 'Malunggay Pandesal', category: RecipeCategory.BREAD, isPopular: false },
  { id: '19', name: 'Pande Amerikana', category: RecipeCategory.BREAD, isPopular: false },
  { id: '20', name: 'Pan de Legaspi', category: RecipeCategory.BREAD, isPopular: false },

  // Cakes & Kakanin (Baked/Steamed)
  { id: '21', name: 'Bibingka Galapong', category: RecipeCategory.CAKE, isPopular: true },
  { id: '22', name: 'Cassava Cake', category: RecipeCategory.CAKE, isPopular: true },
  { id: '23', name: 'Puto Cheese', category: RecipeCategory.CAKE, isPopular: true },
  { id: '24', name: 'Sans Rival', category: RecipeCategory.CAKE, isPopular: true },
  { id: '25', name: 'Brazo de Mercedes', category: RecipeCategory.CAKE, isPopular: true },
  { id: '26', name: 'Ube Macapuno Cake', category: RecipeCategory.CAKE, isPopular: true },
  { id: '27', name: 'Leche Flan (Baked)', category: RecipeCategory.CAKE, isPopular: true },
  { id: '28', name: 'Mamon (Sponge Cake)', category: RecipeCategory.CAKE, isPopular: true },
  { id: '29', name: 'Crema de Fruta', category: RecipeCategory.CAKE, isPopular: true },
  { id: '30', name: 'Egg Pie', category: RecipeCategory.CAKE, isPopular: true },
  { id: '31', name: 'Buko Pie', category: RecipeCategory.CAKE, isPopular: true },
  { id: '32', name: 'Pineapple Upside Down Cake', category: RecipeCategory.CAKE, isPopular: false },
  { id: '33', name: 'Royal Bibingka', category: RecipeCategory.CAKE, isPopular: false },
  { id: '34', name: 'Sapin-Sapin', category: RecipeCategory.CAKE, isPopular: false },
  { id: '35', name: 'Pichu-Pichu', category: RecipeCategory.CAKE, isPopular: false },
  { id: '36', name: 'Inutak', category: RecipeCategory.CAKE, isPopular: false },
  { id: '37', name: 'Budbud Pilipit', category: RecipeCategory.CAKE, isPopular: false },
  { id: '38', name: 'Maja Blanca', category: RecipeCategory.CAKE, isPopular: true },
  { id: '39', name: 'Suman sa Lihiya', category: RecipeCategory.CAKE, isPopular: false },
  { id: '40', name: 'Espasol', category: RecipeCategory.CAKE, isPopular: false },
  
  // Pastries
  { id: '41', name: 'Hopia Baboy', category: RecipeCategory.PASTRY, isPopular: true },
  { id: '42', name: 'Hopia Mongo', category: RecipeCategory.PASTRY, isPopular: true },
  { id: '43', name: 'Hopia Ube', category: RecipeCategory.PASTRY, isPopular: true },
  { id: '44', name: 'Empanada (Chicken)', category: RecipeCategory.PASTRY, isPopular: true },
  { id: '45', name: 'Empanada (Beef)', category: RecipeCategory.PASTRY, isPopular: false },
  { id: '46', name: 'Otap', category: RecipeCategory.PASTRY, isPopular: true },
  { id: '47', name: 'Barquillos', category: RecipeCategory.PASTRY, isPopular: false },
  { id: '48', name: 'Napoleones', category: RecipeCategory.PASTRY, isPopular: true },
  { id: '49', name: 'Piaya', category: RecipeCategory.PASTRY, isPopular: true },
  { id: '50', name: 'Turon (Baked Variation)', category: RecipeCategory.PASTRY, isPopular: true },
  { id: '51', name: 'Banana Cue (Caramelized)', category: RecipeCategory.PASTRY, isPopular: false },
  { id: '52', name: 'Camote Cue', category: RecipeCategory.PASTRY, isPopular: false },
  { id: '53', name: 'Buchi', category: RecipeCategory.PASTRY, isPopular: true },
  { id: '54', name: 'Maruya', category: RecipeCategory.PASTRY, isPopular: false },
  { id: '55', name: 'Carioca', category: RecipeCategory.PASTRY, isPopular: false },
  { id: '56', name: 'Binangkal', category: RecipeCategory.PASTRY, isPopular: false },
  { id: '57', name: 'Shakoy', category: RecipeCategory.PASTRY, isPopular: false },
  { id: '58', name: 'Churros (Pinoy Style)', category: RecipeCategory.PASTRY, isPopular: false },
  { id: '59', name: 'Pilipit', category: RecipeCategory.PASTRY, isPopular: false },
  { id: '60', name: 'Doughnut (Pinoy)', category: RecipeCategory.PASTRY, isPopular: false },

  // Cookies / Biskwit
  { id: '61', name: 'Lengua de Gato', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '62', name: 'Puto Seko', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '63', name: 'Uraro (Arrowroot Cookies)', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '64', name: 'Polvoron', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '65', name: 'Silvanas', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '66', name: 'Broas (Ladyfingers)', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '67', name: 'Pacencia', category: RecipeCategory.COOKIE, isPopular: false },
  { id: '68', name: 'Camachile', category: RecipeCategory.COOKIE, isPopular: false },
  { id: '69', name: 'Galletas de Patatas', category: RecipeCategory.COOKIE, isPopular: false },
  { id: '70', name: 'Jacobina', category: RecipeCategory.COOKIE, isPopular: false },
  { id: '71', name: 'Ogoy-Ogoy', category: RecipeCategory.COOKIE, isPopular: false },
  { id: '72', name: 'Rosquillos', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '73', name: 'Masa Podrida', category: RecipeCategory.COOKIE, isPopular: false },
  { id: '74', name: 'Shing-a-ling', category: RecipeCategory.COOKIE, isPopular: false },
  { id: '75', name: 'Apas', category: RecipeCategory.COOKIE, isPopular: false },
  { id: '76', name: 'Paborita', category: RecipeCategory.COOKIE, isPopular: false },
  { id: '77', name: 'Tipas Hopia', category: RecipeCategory.COOKIE, isPopular: false },
  { id: '78', name: 'Meringue', category: RecipeCategory.COOKIE, isPopular: false },
  { id: '79', name: 'Biscocho', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '80', name: 'Toasted Mamon', category: RecipeCategory.COOKIE, isPopular: false },
  
  // Savory / Others
  { id: '81', name: 'Chicken Pie', category: RecipeCategory.SAVORY, isPopular: true },
  { id: '82', name: 'Tuna Pie', category: RecipeCategory.SAVORY, isPopular: false },
  { id: '83', name: 'Pizza Roll (Pinoy)', category: RecipeCategory.SAVORY, isPopular: false },
  { id: '84', name: 'Ham and Cheese Roll', category: RecipeCategory.SAVORY, isPopular: true },
  { id: '85', name: 'Siopao Asado (Steamed Bun)', category: RecipeCategory.SAVORY, isPopular: true },
  { id: '86', name: 'Siopao Bola-Bola', category: RecipeCategory.SAVORY, isPopular: true },
  { id: '87', name: 'Baked Macaroni (Pinoy Style)', category: RecipeCategory.SAVORY, isPopular: true },
  { id: '88', name: 'Filipino Spaghetti (Baked)', category: RecipeCategory.SAVORY, isPopular: false },
  { id: '89', name: 'Pan de Sal with Corned Beef', category: RecipeCategory.SAVORY, isPopular: false },
  { id: '90', name: 'Toasted Siopao', category: RecipeCategory.SAVORY, isPopular: true },

  // The Final 10 - Modern/Fusion
  { id: '91', name: 'Yema Cake', category: RecipeCategory.CAKE, isPopular: true },
  { id: '92', name: 'Ube Cheese Pandesal', category: RecipeCategory.BREAD, isPopular: true },
  { id: '93', name: 'Choco Crinkles', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '94', name: 'Revel Bars', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '95', name: 'Food for the Gods', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '96', name: 'Banana Bread (Pinoy Style)', category: RecipeCategory.BREAD, isPopular: true },
  { id: '97', name: 'Mango Bravo Copycat', category: RecipeCategory.CAKE, isPopular: true },
  { id: '98', name: 'Ube Halaya', category: RecipeCategory.CAKE, isPopular: true },
  { id: '99', name: 'Pastillas de Leche', category: RecipeCategory.COOKIE, isPopular: true },
  { id: '100', name: 'Cathedral Window Jelly', category: RecipeCategory.CAKE, isPopular: false },
];